#
# Example Config file
#

name: 'Backend Users'

#
# State
# - "prod"  run in stage "prod"
# - "dev"   run in stage "dev"
#
stage: 'dev'

# Section http
http:
  port: 8080
  host: '0.0.0.0'

# Section "log"
log:
  level: 'debug'

#
# Database section
database:
  host: 'localhost'
  port: 3306
  user: 'users'
  password: 'users1234'
  database: 'users'
